services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gridtrack-backend
    restart: always
    ports:
      - "22843:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://grid:strongpassword@187.127.139.208:5432/biometric
      - JWT_SECRET=stopreadingthesecret
      - R2_ACCOUNT_ID=bdce6341de1e7b4818a4832fbe29d68c
      - R2_ACCESS_KEY_ID=28fb692bc554c8feb96a963c00bbc3e1
      - R2_SECRET_ACCESS_KEY=2f73fcce066c3c441c3f15d25827892aa6371934de593ebaf4658be7758aa199
      - R2_BUCKET_NAME=tracker
      - MIN_SCREENSHOT_INTERVAL=60
      - MAX_SCREENSHOT_INTERVAL=300
    networks:
      - gridtrack_network

networks:
  gridtrack_network:
    driver: bridge